
python gpt2_multi_task.py \
  --data_dir "../data/" \
  --model_dir "gpt2" \
  --save_dir "./output/saved_model" \
  --log_dir "./output/log" \
  --train "train_full.jsonl" \
  --dev "dev_full.jsonl" \
  --test "dev_full.jsonl" \
  --model_name "gpt2" \
  --gpu "0" \
  --batch_size 32 \
  --cuda True\
  --epochs 10 \
  --lr 2e-5 \
  --set_seed True \
  --seed 1024 \
  --patient 5 \
  --length 22 \
  --alpha 0.9 \
  --beam_size 5 \
  --no_repeat_ngram_size 3 \
  --repetition_penalty 1.5 \
  --do_sample True \
  --mode "discriminate_generate" \
